name: TheyLendMe
description: App de préstamos entre individuos y grupos.

version: 1.0.0+1 # versión de nuestra app

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  image_picker:
  validate: ^1.4.0
  #PRUEBAS de AUTENTICACIÓN: '$ flutter run' y después descomentar (1º)
  #firebase_auth: ^0.5.20
  #firebase_core: ^0.2.5+1
  #google_sign_in: ^3.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  #
  # For details:
  # https://flutter.io/assets-and-images

  # To add custom fonts to your application:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details:
  # see https://flutter.io/custom-fonts
